/**
 * 元素扩展数据：91-118号元素（放射性元素）
 */

module.exports = {
  91: { electronAffinity: 30, oxidationStates: [3, 4, 5], density: 15.37, electronConfig: '[Rn] 5f² 6d¹ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 5, crystalStructure: '四方', magneticOrdering: '顺磁性', thermalConductivity: 47, specificHeat: 27.7 },
  92: { electronAffinity: 30, oxidationStates: [1, 2, 3, 4, 5, 6], density: 18.95, electronConfig: '[Rn] 5f³ 6d¹ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 6, crystalStructure: '正交', magneticOrdering: '顺磁性', thermalConductivity: 27.5, specificHeat: 27.665 },
  93: { electronAffinity: 30, oxidationStates: [2, 3, 4, 5, 6, 7], density: 20.45, electronConfig: '[Rn] 5f⁴ 6d¹ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 7, crystalStructure: '正交', magneticOrdering: '顺磁性', thermalConductivity: 6.3, specificHeat: 29.46 },
  94: { electronAffinity: 30, oxidationStates: [2, 3, 4, 5, 6, 7], density: 19.84, electronConfig: '[Rn] 5f⁶ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 6, crystalStructure: '单斜', magneticOrdering: '顺磁性', thermalConductivity: 6.74, specificHeat: 35.5 },
  95: { electronAffinity: 30, oxidationStates: [2, 3, 4, 5, 6, 7], density: 13.69, electronConfig: '[Rn] 5f⁷ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 7, crystalStructure: '六方密堆积', magneticOrdering: '顺磁性', thermalConductivity: 10, specificHeat: 62.7 },
  96: { electronAffinity: 30, oxidationStates: [3, 4, 5, 6], density: 13.51, electronConfig: '[Rn] 5f⁷ 6d¹ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 8, crystalStructure: '六方密堆积', magneticOrdering: '顺磁性', thermalConductivity: 8.8, specificHeat: 27.7 },
  97: { electronAffinity: 30, oxidationStates: [3, 4], density: 14.78, electronConfig: '[Rn] 5f⁹ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 9, crystalStructure: '六方密堆积', magneticOrdering: '顺磁性', thermalConductivity: 10, specificHeat: 28 },
  98: { electronAffinity: 30, oxidationStates: [2, 3, 4], density: 15.1, electronConfig: '[Rn] 5f¹⁰ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 10, crystalStructure: '六方密堆积', magneticOrdering: '顺磁性', thermalConductivity: 10, specificHeat: 27 },
  99: { electronAffinity: 30, oxidationStates: [2, 3, 4], density: 8.84, electronConfig: '[Rn] 5f¹¹ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 11, crystalStructure: '面心立方', magneticOrdering: '顺磁性', thermalConductivity: 10, specificHeat: 28 },
  100: { electronAffinity: 30, oxidationStates: [2, 3], density: 9.7, electronConfig: '[Rn] 5f¹² 7s²', group: null, period: 7, block: 'f', valenceElectrons: 12, crystalStructure: '面心立方', magneticOrdering: '顺磁性', thermalConductivity: 10, specificHeat: 27 },
  101: { electronAffinity: 30, oxidationStates: [2, 3], density: 10, electronConfig: '[Rn] 5f¹³ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 13, crystalStructure: '面心立方', magneticOrdering: '顺磁性', thermalConductivity: 10, specificHeat: 27 },
  102: { electronAffinity: 30, oxidationStates: [2, 3], density: 10, electronConfig: '[Rn] 5f¹⁴ 7s²', group: null, period: 7, block: 'f', valenceElectrons: 14, crystalStructure: '六方密堆积', magneticOrdering: '顺磁性', thermalConductivity: 10, specificHeat: 27 },
  103: { electronAffinity: 30, oxidationStates: [3], density: 15.6, electronConfig: '[Rn] 5f¹⁴ 6d¹ 7s²', group: 3, period: 7, block: 'd', valenceElectrons: 3, crystalStructure: '六方密堆积', magneticOrdering: '顺磁性', thermalConductivity: 10, specificHeat: 27 },
  104: { electronAffinity: 0, oxidationStates: [4], density: 23.2, electronConfig: '[Rn] 5f¹⁴ 6d² 7s²', group: 4, period: 7, block: 'd', valenceElectrons: 4, crystalStructure: '六方密堆积', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  105: { electronAffinity: 0, oxidationStates: [5], density: 29.3, electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²', group: 5, period: 7, block: 'd', valenceElectrons: 5, crystalStructure: '体心立方', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  106: { electronAffinity: 0, oxidationStates: [6], density: 35.0, electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²', group: 6, period: 7, block: 'd', valenceElectrons: 6, crystalStructure: '体心立方', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  107: { electronAffinity: 0, oxidationStates: [7], density: 37.1, electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²', group: 7, period: 7, block: 'd', valenceElectrons: 7, crystalStructure: '六方密堆积', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  108: { electronAffinity: 0, oxidationStates: [8], density: 40.7, electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²', group: 8, period: 7, block: 'd', valenceElectrons: 8, crystalStructure: '六方密堆积', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  109: { electronAffinity: 0, oxidationStates: [9], density: 37.4, electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²', group: 9, period: 7, block: 'd', valenceElectrons: 9, crystalStructure: '面心立方', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  110: { electronAffinity: 0, oxidationStates: [2], density: 34.8, electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s¹', group: 10, period: 7, block: 'd', valenceElectrons: 10, crystalStructure: '面心立方', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  111: { electronAffinity: 0, oxidationStates: [1, 3], density: 28.7, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s¹', group: 11, period: 7, block: 'd', valenceElectrons: 11, crystalStructure: '面心立方', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  112: { electronAffinity: 0, oxidationStates: [2, 4], density: 23.7, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', group: 12, period: 7, block: 'd', valenceElectrons: 12, crystalStructure: '菱形', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  113: { electronAffinity: 0, oxidationStates: [1, 3], density: 16, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', group: 13, period: 7, block: 'p', valenceElectrons: 3, crystalStructure: '未知', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  114: { electronAffinity: 0, oxidationStates: [2, 4], density: 14, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', group: 14, period: 7, block: 'p', valenceElectrons: 4, crystalStructure: '未知', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  115: { electronAffinity: 0, oxidationStates: [1, 3], density: 13.5, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', group: 15, period: 7, block: 'p', valenceElectrons: 5, crystalStructure: '未知', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  116: { electronAffinity: 0, oxidationStates: [2, 4], density: 12.9, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', group: 16, period: 7, block: 'p', valenceElectrons: 6, crystalStructure: '未知', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  117: { electronAffinity: 0, oxidationStates: [1, 3, 5], density: 7.2, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', group: 17, period: 7, block: 'p', valenceElectrons: 7, crystalStructure: '未知', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null },
  118: { electronAffinity: 0, oxidationStates: [0, 2, 4, 6], density: 5, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', group: 18, period: 7, block: 'p', valenceElectrons: 8, crystalStructure: '未知', magneticOrdering: '未知', thermalConductivity: null, specificHeat: null }
};

