/**
 * 元素扩展数据：1-30号元素
 * 详细数据：常见元素
 */

module.exports = {
  1: { // H 氢
    electronAffinity: 72.8,
    oxidationStates: [-1, 1],
    density: 0.00008988,
    electronConfig: '1s¹',
    group: 1, period: 1, block: 's',
    valenceElectrons: 1,
    crystalStructure: '六方密堆积',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.1805,
    specificHeat: 14.304
  },
  2: { // He 氦
    electronAffinity: 0,
    oxidationStates: [0],
    density: 0.0001785,
    electronConfig: '1s²',
    group: 18, period: 1, block: 's',
    valenceElectrons: 2,
    crystalStructure: '六方密堆积',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.1513,
    specificHeat: 20.786
  },
  3: { // Li 锂
    electronAffinity: 59.6,
    oxidationStates: [1],
    density: 0.534,
    electronConfig: '[He] 2s¹',
    group: 1, period: 2, block: 's',
    valenceElectrons: 1,
    crystalStructure: '体心立方',
    magneticOrdering: '顺磁性',
    thermalConductivity: 84.8,
    specificHeat: 24.860
  },
  4: { // Be 铍
    electronAffinity: 0,
    oxidationStates: [2],
    density: 1.85,
    electronConfig: '[He] 2s²',
    group: 2, period: 2, block: 's',
    valenceElectrons: 2,
    crystalStructure: '六方密堆积',
    magneticOrdering: '反磁性',
    thermalConductivity: 200,
    specificHeat: 16.443
  },
  5: { // B 硼
    electronAffinity: 26.7,
    oxidationStates: [-5, -1, 1, 2, 3],
    density: 2.34,
    electronConfig: '[He] 2s² 2p¹',
    group: 13, period: 2, block: 'p',
    valenceElectrons: 3,
    crystalStructure: '菱形',
    magneticOrdering: '反磁性',
    thermalConductivity: 27,
    specificHeat: 11.087
  },
  6: { // C 碳
    electronAffinity: 153.9,
    oxidationStates: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
    density: 2.267,
    electronConfig: '[He] 2s² 2p²',
    group: 14, period: 2, block: 'p',
    valenceElectrons: 4,
    crystalStructure: '六方（石墨）/立方（金刚石）',
    magneticOrdering: '反磁性',
    thermalConductivity: 129,
    specificHeat: 8.517
  },
  7: { // N 氮
    electronAffinity: 7,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5],
    density: 0.0012506,
    electronConfig: '[He] 2s² 2p³',
    group: 15, period: 2, block: 'p',
    valenceElectrons: 5,
    crystalStructure: '六方',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.02583,
    specificHeat: 29.124
  },
  8: { // O 氧
    electronAffinity: 141,
    oxidationStates: [-2, -1, 1, 2],
    density: 0.001429,
    electronConfig: '[He] 2s² 2p⁴',
    group: 16, period: 2, block: 'p',
    valenceElectrons: 6,
    crystalStructure: '立方',
    magneticOrdering: '顺磁性',
    thermalConductivity: 0.02658,
    specificHeat: 29.378
  },
  9: { // F 氟
    electronAffinity: 328,
    oxidationStates: [-1],
    density: 0.001696,
    electronConfig: '[He] 2s² 2p⁵',
    group: 17, period: 2, block: 'p',
    valenceElectrons: 7,
    crystalStructure: '单斜',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.0277,
    specificHeat: 31.304
  },
  10: { // Ne 氖
    electronAffinity: 0,
    oxidationStates: [0],
    density: 0.0008999,
    electronConfig: '[He] 2s² 2p⁶',
    group: 18, period: 2, block: 'p',
    valenceElectrons: 8,
    crystalStructure: '面心立方',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.0491,
    specificHeat: 20.786
  },
  11: { // Na 钠
    electronAffinity: 52.8,
    oxidationStates: [-1, 1],
    density: 0.971,
    electronConfig: '[Ne] 3s¹',
    group: 1, period: 3, block: 's',
    valenceElectrons: 1,
    crystalStructure: '体心立方',
    magneticOrdering: '顺磁性',
    thermalConductivity: 142,
    specificHeat: 28.230
  },
  12: { // Mg 镁
    electronAffinity: 0,
    oxidationStates: [1, 2],
    density: 1.738,
    electronConfig: '[Ne] 3s²',
    group: 2, period: 3, block: 's',
    valenceElectrons: 2,
    crystalStructure: '六方密堆积',
    magneticOrdering: '顺磁性',
    thermalConductivity: 156,
    specificHeat: 24.869
  },
  13: { // Al 铝
    electronAffinity: 42.5,
    oxidationStates: [-2, -1, 1, 2, 3],
    density: 2.698,
    electronConfig: '[Ne] 3s² 3p¹',
    group: 13, period: 3, block: 'p',
    valenceElectrons: 3,
    crystalStructure: '面心立方',
    magneticOrdering: '顺磁性',
    thermalConductivity: 237,
    specificHeat: 24.200
  },
  14: { // Si 硅
    electronAffinity: 133.6,
    oxidationStates: [-4, -3, -2, -1, 1, 2, 3, 4],
    density: 2.3296,
    electronConfig: '[Ne] 3s² 3p²',
    group: 14, period: 3, block: 'p',
    valenceElectrons: 4,
    crystalStructure: '金刚石型立方',
    magneticOrdering: '反磁性',
    thermalConductivity: 149,
    specificHeat: 19.789
  },
  15: { // P 磷
    electronAffinity: 72,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5],
    density: 1.82,
    electronConfig: '[Ne] 3s² 3p³',
    group: 15, period: 3, block: 'p',
    valenceElectrons: 5,
    crystalStructure: '三斜/立方/单斜',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.236,
    specificHeat: 23.824
  },
  16: { // S 硫
    electronAffinity: 200,
    oxidationStates: [-2, -1, 1, 2, 3, 4, 5, 6],
    density: 2.067,
    electronConfig: '[Ne] 3s² 3p⁴',
    group: 16, period: 3, block: 'p',
    valenceElectrons: 6,
    crystalStructure: '正交',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.205,
    specificHeat: 22.75
  },
  17: { // Cl 氯
    electronAffinity: 349,
    oxidationStates: [-1, 1, 2, 3, 4, 5, 6, 7],
    density: 0.003214,
    electronConfig: '[Ne] 3s² 3p⁵',
    group: 17, period: 3, block: 'p',
    valenceElectrons: 7,
    crystalStructure: '正交',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.0089,
    specificHeat: 33.949
  },
  18: { // Ar 氩
    electronAffinity: 0,
    oxidationStates: [0],
    density: 0.0017837,
    electronConfig: '[Ne] 3s² 3p⁶',
    group: 18, period: 3, block: 'p',
    valenceElectrons: 8,
    crystalStructure: '面心立方',
    magneticOrdering: '反磁性',
    thermalConductivity: 0.01772,
    specificHeat: 20.786
  },
  19: { // K 钾
    electronAffinity: 48.4,
    oxidationStates: [-1, 1],
    density: 0.862,
    electronConfig: '[Ar] 4s¹',
    group: 1, period: 4, block: 's',
    valenceElectrons: 1,
    crystalStructure: '体心立方',
    magneticOrdering: '顺磁性',
    thermalConductivity: 102.5,
    specificHeat: 29.600
  },
  20: { // Ca 钙
    electronAffinity: 2.37,
    oxidationStates: [1, 2],
    density: 1.54,
    electronConfig: '[Ar] 4s²',
    group: 2, period: 4, block: 's',
    valenceElectrons: 2,
    crystalStructure: '面心立方',
    magneticOrdering: '顺磁性',
    thermalConductivity: 201,
    specificHeat: 25.929
  },
  21: { // Sc 钪
    electronAffinity: 18,
    oxidationStates: [1, 2, 3],
    density: 2.989,
    electronConfig: '[Ar] 3d¹ 4s²',
    group: 3, period: 4, block: 'd',
    valenceElectrons: 3,
    crystalStructure: '六方密堆积',
    magneticOrdering: '顺磁性',
    thermalConductivity: 15.8,
    specificHeat: 25.52
  },
  22: { // Ti 钛
    electronAffinity: 7.6,
    oxidationStates: [-2, -1, 1, 2, 3, 4],
    density: 4.54,
    electronConfig: '[Ar] 3d² 4s²',
    group: 4, period: 4, block: 'd',
    valenceElectrons: 4,
    crystalStructure: '六方密堆积',
    magneticOrdering: '顺磁性',
    thermalConductivity: 21.9,
    specificHeat: 25.060
  },
  23: { // V 钒
    electronAffinity: 50.6,
    oxidationStates: [-3, -1, 1, 2, 3, 4, 5],
    density: 6.11,
    electronConfig: '[Ar] 3d³ 4s²',
    group: 5, period: 4, block: 'd',
    valenceElectrons: 5,
    crystalStructure: '体心立方',
    magneticOrdering: '顺磁性',
    thermalConductivity: 30.7,
    specificHeat: 24.89
  },
  24: { // Cr 铬
    electronAffinity: 64.3,
    oxidationStates: [-4, -2, -1, 1, 2, 3, 4, 5, 6],
    density: 7.15,
    electronConfig: '[Ar] 3d⁵ 4s¹',
    group: 6, period: 4, block: 'd',
    valenceElectrons: 6,
    crystalStructure: '体心立方',
    magneticOrdering: '反铁磁性',
    thermalConductivity: 93.9,
    specificHeat: 23.35
  },
  25: { // Mn 锰
    electronAffinity: 0,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5, 6, 7],
    density: 7.44,
    electronConfig: '[Ar] 3d⁵ 4s²',
    group: 7, period: 4, block: 'd',
    valenceElectrons: 7,
    crystalStructure: '立方',
    magneticOrdering: '顺磁性',
    thermalConductivity: 7.81,
    specificHeat: 26.32
  },
  26: { // Fe 铁
    electronAffinity: 15.7,
    oxidationStates: [-4, -2, -1, 1, 2, 3, 4, 5, 6, 7],
    density: 7.874,
    electronConfig: '[Ar] 3d⁶ 4s²',
    group: 8, period: 4, block: 'd',
    valenceElectrons: 8,
    crystalStructure: '体心立方',
    magneticOrdering: '铁磁性',
    thermalConductivity: 80.4,
    specificHeat: 25.10
  },
  27: { // Co 钴
    electronAffinity: 63.7,
    oxidationStates: [-3, -1, 1, 2, 3, 4, 5],
    density: 8.86,
    electronConfig: '[Ar] 3d⁷ 4s²',
    group: 9, period: 4, block: 'd',
    valenceElectrons: 9,
    crystalStructure: '六方密堆积',
    magneticOrdering: '铁磁性',
    thermalConductivity: 100,
    specificHeat: 24.81
  },
  28: { // Ni 镍
    electronAffinity: 112,
    oxidationStates: [-2, -1, 1, 2, 3, 4],
    density: 8.912,
    electronConfig: '[Ar] 3d⁸ 4s²',
    group: 10, period: 4, block: 'd',
    valenceElectrons: 10,
    crystalStructure: '面心立方',
    magneticOrdering: '铁磁性',
    thermalConductivity: 90.9,
    specificHeat: 26.07
  },
  29: { // Cu 铜
    electronAffinity: 118.4,
    oxidationStates: [-2, 1, 2, 3, 4],
    density: 8.96,
    electronConfig: '[Ar] 3d¹⁰ 4s¹',
    group: 11, period: 4, block: 'd',
    valenceElectrons: 11,
    crystalStructure: '面心立方',
    magneticOrdering: '反磁性',
    thermalConductivity: 401,
    specificHeat: 24.440
  },
  30: { // Zn 锌
    electronAffinity: 0,
    oxidationStates: [-2, 1, 2],
    density: 7.134,
    electronConfig: '[Ar] 3d¹⁰ 4s²',
    group: 12, period: 4, block: 'd',
    valenceElectrons: 12,
    crystalStructure: '六方密堆积',
    magneticOrdering: '反磁性',
    thermalConductivity: 116,
    specificHeat: 25.470
  }
};

